org.gradle.jvmargs=-Xmx4G
minecraft_version=26.2
loader_version=0.19.3
maven_group=org.hendrix.betterpalegarden
archives_base_name=BetterPaleGarden
fabric_version=0.152.1
cloth_config_version=26.2.155
mod_menu_version=20.0.0-beta.1
mod_id=betterpalegarden
mod_version=1.6-Fabric
mod_name=Hendrix's Better Pale Garden
mod_description=Boost the Pale Garden with White Pumpkins, new Resin Blocks and a new Structure!
mod_author=JimiIT92
mod_url=https://github.com/JimiIT92/BetterPaleGarden
loom_version=1.17-SNAPSHOT